// Skill action tables. Each entry maps a scoreboard objective to the
// vanilla statistic it tracks and the xp granted per event.
//
// Extracted from the pre-TypeScript datapack; extend freely.

export interface Action {
  readonly objective: string;
  readonly criteria: string;
  readonly xp: number;
  /** Divide the statistic delta by this before granting xp. Used for
   *  distance-based custom stats (e.g. `fall_one_cm`) whose raw delta is far
   *  larger than one "event". The value must exist as a holder in
   *  `dps_globals`. */
  readonly divisor?: number;
}

export const ACTIONS = {
  combat: [
    { objective: "dps_zombie", criteria: "minecraft.killed:minecraft.zombie", xp: 1 },
    { objective: "dps_skeleton", criteria: "minecraft.killed:minecraft.skeleton", xp: 1 },
    { objective: "dps_spider", criteria: "minecraft.killed:minecraft.spider", xp: 1 },
    { objective: "dps_cave_spider", criteria: "minecraft.killed:minecraft.cave_spider", xp: 1 },
    { objective: "dps_silverfish", criteria: "minecraft.killed:minecraft.silverfish", xp: 1 },
    { objective: "dps_endermite", criteria: "minecraft.killed:minecraft.endermite", xp: 1 },
    { objective: "dps_wolf", criteria: "minecraft.killed:minecraft.wolf", xp: 1 },
    { objective: "dps_fox", criteria: "minecraft.killed:minecraft.fox", xp: 1 },
    { objective: "dps_cat", criteria: "minecraft.killed:minecraft.cat", xp: 1 },
    { objective: "dps_chicken", criteria: "minecraft.killed:minecraft.chicken", xp: 1 },
    { objective: "dps_cow", criteria: "minecraft.killed:minecraft.cow", xp: 1 },
    { objective: "dps_pig", criteria: "minecraft.killed:minecraft.pig", xp: 1 },
    { objective: "dps_sheep", criteria: "minecraft.killed:minecraft.sheep", xp: 1 },
    { objective: "dps_rabbit", criteria: "minecraft.killed:minecraft.rabbit", xp: 1 },
    { objective: "dps_turtle", criteria: "minecraft.killed:minecraft.turtle", xp: 1 },
    { objective: "dps_squid", criteria: "minecraft.killed:minecraft.squid", xp: 1 },
    { objective: "dps_cod", criteria: "minecraft.killed:minecraft.cod", xp: 1 },
    { objective: "dps_salmon", criteria: "minecraft.killed:minecraft.salmon", xp: 1 },
    { objective: "dps_tropical_fish", criteria: "minecraft.killed:minecraft.tropical_fish", xp: 1 },
    { objective: "dps_pufferfish", criteria: "minecraft.killed:minecraft.pufferfish", xp: 1 },
    { objective: "dps_llama", criteria: "minecraft.killed:minecraft.llama", xp: 1 },
    { objective: "dps_trader_llama", criteria: "minecraft.killed:minecraft.trader_llama", xp: 1 },
    { objective: "dps_villager", criteria: "minecraft.killed:minecraft.villager", xp: 1 },
    { objective: "dps_wandering_trader", criteria: "minecraft.killed:minecraft.wandering_trader", xp: 1 },
    { objective: "dps_husk", criteria: "minecraft.killed:minecraft.husk", xp: 2 },
    { objective: "dps_stray", criteria: "minecraft.killed:minecraft.stray", xp: 2 },
    { objective: "dps_drowned", criteria: "minecraft.killed:minecraft.drowned", xp: 2 },
    { objective: "dps_pillager", criteria: "minecraft.killed:minecraft.pillager", xp: 2 },
    { objective: "dps_vindicator", criteria: "minecraft.killed:minecraft.vindicator", xp: 2 },
    { objective: "dps_evoker", criteria: "minecraft.killed:minecraft.evoker", xp: 2 },
    { objective: "dps_vex", criteria: "minecraft.killed:minecraft.vex", xp: 2 },
    { objective: "dps_witch", criteria: "minecraft.killed:minecraft.witch", xp: 2 },
    { objective: "dps_polar_bear", criteria: "minecraft.killed:minecraft.polar_bear", xp: 2 },
    { objective: "dps_piglin", criteria: "minecraft.killed:minecraft.piglin", xp: 2 },
    { objective: "dps_piglin_brute", criteria: "minecraft.killed:minecraft.piglin_brute", xp: 2 },
    { objective: "dps_strider", criteria: "minecraft.killed:minecraft.strider", xp: 2 },
    { objective: "dps_creeper", criteria: "minecraft.killed:minecraft.creeper", xp: 3 },
    { objective: "dps_slime", criteria: "minecraft.killed:minecraft.slime", xp: 3 },
    { objective: "dps_magma_cube", criteria: "minecraft.killed:minecraft.magma_cube", xp: 3 },
    { objective: "dps_enderman", criteria: "minecraft.killed:minecraft.enderman", xp: 3 },
    { objective: "dps_blaze", criteria: "minecraft.killed:minecraft.blaze", xp: 3 },
    { objective: "dps_ghast", criteria: "minecraft.killed:minecraft.ghast", xp: 3 },
    { objective: "dps_shulker", criteria: "minecraft.killed:minecraft.shulker", xp: 3 },
    { objective: "dps_wither_skeleton", criteria: "minecraft.killed:minecraft.wither_skeleton", xp: 3 },
    { objective: "dps_guardian", criteria: "minecraft.killed:minecraft.guardian", xp: 3 },
    { objective: "dps_elder_guardian", criteria: "minecraft.killed:minecraft.elder_guardian", xp: 4 },
    { objective: "dps_wither", criteria: "minecraft.killed:minecraft.wither", xp: 4 },
    { objective: "dps_ender_dragon", criteria: "minecraft.killed:minecraft.ender_dragon", xp: 4 },
  ],
  digging: [
    { objective: "dps_coarse_dirt", criteria: "minecraft.mined:minecraft.coarse_dirt", xp: 1 },
    { objective: "dps_dirt", criteria: "minecraft.mined:minecraft.dirt", xp: 1 },
    { objective: "dps_farmland", criteria: "minecraft.mined:minecraft.farmland", xp: 1 },
    { objective: "dps_grass_block", criteria: "minecraft.mined:minecraft.grass_block", xp: 1 },
    { objective: "dps_gravel", criteria: "minecraft.mined:minecraft.gravel", xp: 1 },
    { objective: "dps_podzol", criteria: "minecraft.mined:minecraft.podzol", xp: 1 },
    { objective: "dps_red_sand", criteria: "minecraft.mined:minecraft.red_sand", xp: 1 },
    { objective: "dps_rooted_dirt", criteria: "minecraft.mined:minecraft.rooted_dirt", xp: 1 },
    { objective: "dps_sand", criteria: "minecraft.mined:minecraft.sand", xp: 1 },
    { objective: "dps_snow", criteria: "minecraft.mined:minecraft.snow", xp: 1 },
    { objective: "dps_snow_block", criteria: "minecraft.mined:minecraft.snow_block", xp: 1 },
    { objective: "dps_suspicious_gravel", criteria: "minecraft.mined:minecraft.suspicious_gravel", xp: 1 },
    { objective: "dps_suspicious_sand", criteria: "minecraft.mined:minecraft.suspicious_sand", xp: 1 },
    { objective: "dps_clay", criteria: "minecraft.mined:minecraft.clay", xp: 2 },
    { objective: "dps_white_concrete_powder", criteria: "minecraft.mined:minecraft.white_concrete_powder", xp: 2 },
    { objective: "dps_light_gray_concrete_powder", criteria: "minecraft.mined:minecraft.light_gray_concrete_powder", xp: 2 },
    { objective: "dps_gray_concrete_powder", criteria: "minecraft.mined:minecraft.gray_concrete_powder", xp: 2 },
    { objective: "dps_black_concrete_powder", criteria: "minecraft.mined:minecraft.black_concrete_powder", xp: 2 },
    { objective: "dps_brown_concrete_powder", criteria: "minecraft.mined:minecraft.brown_concrete_powder", xp: 2 },
    { objective: "dps_red_concrete_powder", criteria: "minecraft.mined:minecraft.red_concrete_powder", xp: 2 },
    { objective: "dps_orange_concrete_powder", criteria: "minecraft.mined:minecraft.orange_concrete_powder", xp: 2 },
    { objective: "dps_yellow_concrete_powder", criteria: "minecraft.mined:minecraft.yellow_concrete_powder", xp: 2 },
    { objective: "dps_lime_concrete_powder", criteria: "minecraft.mined:minecraft.lime_concrete_powder", xp: 2 },
    { objective: "dps_green_concrete_powder", criteria: "minecraft.mined:minecraft.green_concrete_powder", xp: 2 },
    { objective: "dps_cyan_concrete_powder", criteria: "minecraft.mined:minecraft.cyan_concrete_powder", xp: 2 },
    { objective: "dps_light_blue_concrete_powder", criteria: "minecraft.mined:minecraft.light_blue_concrete_powder", xp: 2 },
    { objective: "dps_blue_concrete_powder", criteria: "minecraft.mined:minecraft.blue_concrete_powder", xp: 2 },
    { objective: "dps_purple_concrete_powder", criteria: "minecraft.mined:minecraft.purple_concrete_powder", xp: 2 },
    { objective: "dps_magenta_concrete_powder", criteria: "minecraft.mined:minecraft.magenta_concrete_powder", xp: 2 },
    { objective: "dps_pink_concrete_powder", criteria: "minecraft.mined:minecraft.pink_concrete_powder", xp: 2 },
    { objective: "dps_mud", criteria: "minecraft.mined:minecraft.mud", xp: 2 },
    { objective: "dps_muddy_mangrove_roots", criteria: "minecraft.mined:minecraft.muddy_mangrove_roots", xp: 2 },
    { objective: "dps_mycelium", criteria: "minecraft.mined:minecraft.mycelium", xp: 2 },
    { objective: "dps_soul_sand", criteria: "minecraft.mined:minecraft.soul_sand", xp: 3 },
    { objective: "dps_soul_soil", criteria: "minecraft.mined:minecraft.soul_soil", xp: 3 },
  ],
  mining: [
    { objective: "dps_stone", criteria: "minecraft.mined:minecraft.stone", xp: 1 },
    { objective: "dps_cobblestone", criteria: "minecraft.mined:minecraft.cobblestone", xp: 1 },
    { objective: "dps_mossy_cobblestone", criteria: "minecraft.mined:minecraft.mossy_cobblestone", xp: 1 },
    { objective: "dps_andesite", criteria: "minecraft.mined:minecraft.andesite", xp: 1 },
    { objective: "dps_diorite", criteria: "minecraft.mined:minecraft.diorite", xp: 1 },
    { objective: "dps_granite", criteria: "minecraft.mined:minecraft.granite", xp: 1 },
    { objective: "dps_tuff", criteria: "minecraft.mined:minecraft.tuff", xp: 1 },
    { objective: "dps_calcite", criteria: "minecraft.mined:minecraft.calcite", xp: 1 },
    { objective: "dps_dripstone_block", criteria: "minecraft.mined:minecraft.dripstone_block", xp: 1 },
    { objective: "dps_smooth_basalt", criteria: "minecraft.mined:minecraft.smooth_basalt", xp: 1 },
    { objective: "dps_basalt", criteria: "minecraft.mined:minecraft.basalt", xp: 1 },
    { objective: "dps_end_stone", criteria: "minecraft.mined:minecraft.end_stone", xp: 1 },
    { objective: "dps_netherrack", criteria: "minecraft.mined:minecraft.netherrack", xp: 1 },
    { objective: "dps_packed_ice", criteria: "minecraft.mined:minecraft.packed_ice", xp: 1 },
    { objective: "dps_ice", criteria: "minecraft.mined:minecraft.ice", xp: 1 },
    { objective: "dps_deepslate", criteria: "minecraft.mined:minecraft.deepslate", xp: 1 },
    { objective: "dps_coal_ore", criteria: "minecraft.mined:minecraft.coal_ore", xp: 2 },
    { objective: "dps_deepslate_coal_ore", criteria: "minecraft.mined:minecraft.deepslate_coal_ore", xp: 2 },
    { objective: "dps_copper_ore", criteria: "minecraft.mined:minecraft.copper_ore", xp: 2 },
    { objective: "dps_deepslate_copper_ore", criteria: "minecraft.mined:minecraft.deepslate_copper_ore", xp: 2 },
    { objective: "dps_quartz_ore", criteria: "minecraft.mined:minecraft.nether_quartz_ore", xp: 2 },
    { objective: "dps_nether_gold_ore", criteria: "minecraft.mined:minecraft.nether_gold_ore", xp: 2 },
    { objective: "dps_magma_block", criteria: "minecraft.mined:minecraft.magma_block", xp: 2 },
    { objective: "dps_amethyst_cluster", criteria: "minecraft.mined:minecraft.amethyst_cluster", xp: 2 },
    { objective: "dps_large_amethyst_bud", criteria: "minecraft.mined:minecraft.large_amethyst_bud", xp: 2 },
    { objective: "dps_medium_amethyst_bud", criteria: "minecraft.mined:minecraft.medium_amethyst_bud", xp: 2 },
    { objective: "dps_small_amethyst_bud", criteria: "minecraft.mined:minecraft.small_amethyst_bud", xp: 2 },
    { objective: "dps_iron_ore", criteria: "minecraft.mined:minecraft.iron_ore", xp: 3 },
    { objective: "dps_deepslate_iron_ore", criteria: "minecraft.mined:minecraft.deepslate_iron_ore", xp: 3 },
    { objective: "dps_lapis_ore", criteria: "minecraft.mined:minecraft.lapis_ore", xp: 3 },
    { objective: "dps_deepslate_lapis_ore", criteria: "minecraft.mined:minecraft.deepslate_lapis_ore", xp: 3 },
    { objective: "dps_gold_ore", criteria: "minecraft.mined:minecraft.gold_ore", xp: 3 },
    { objective: "dps_deepslate_gold_ore", criteria: "minecraft.mined:minecraft.deepslate_gold_ore", xp: 3 },
    { objective: "dps_redstone_ore", criteria: "minecraft.mined:minecraft.redstone_ore", xp: 3 },
    { objective: "dps_deepslate_redstone_ore", criteria: "minecraft.mined:minecraft.deepslate_redstone_ore", xp: 3 },
    { objective: "dps_diamond_ore", criteria: "minecraft.mined:minecraft.diamond_ore", xp: 4 },
    { objective: "dps_deepslate_diamond_ore", criteria: "minecraft.mined:minecraft.deepslate_diamond_ore", xp: 4 },
    { objective: "dps_emerald_ore", criteria: "minecraft.mined:minecraft.emerald_ore", xp: 4 },
    { objective: "dps_deepslate_emerald_ore", criteria: "minecraft.mined:minecraft.deepslate_emerald_ore", xp: 4 },
    { objective: "dps_ancient_debris", criteria: "minecraft.mined:minecraft.ancient_debris", xp: 4 },
  ],
  woodcutting: [
    { objective: "dps_oak_log", criteria: "minecraft.mined:minecraft.oak_log", xp: 1 },
    { objective: "dps_spruce_log", criteria: "minecraft.mined:minecraft.spruce_log", xp: 1 },
    { objective: "dps_birch_log", criteria: "minecraft.mined:minecraft.birch_log", xp: 1 },
    { objective: "dps_jungle_log", criteria: "minecraft.mined:minecraft.jungle_log", xp: 1 },
    { objective: "dps_acacia_log", criteria: "minecraft.mined:minecraft.acacia_log", xp: 1 },
    { objective: "dps_dark_oak_log", criteria: "minecraft.mined:minecraft.dark_oak_log", xp: 1 },
    { objective: "dps_mangrove_log", criteria: "minecraft.mined:minecraft.mangrove_log", xp: 1 },
    { objective: "dps_cherry_log", criteria: "minecraft.mined:minecraft.cherry_log", xp: 1 },
    { objective: "dps_stripped_oak_log", criteria: "minecraft.mined:minecraft.stripped_oak_log", xp: 1 },
    { objective: "dps_stripped_spruce_log", criteria: "minecraft.mined:minecraft.stripped_spruce_log", xp: 1 },
    { objective: "dps_stripped_birch_log", criteria: "minecraft.mined:minecraft.stripped_birch_log", xp: 1 },
    { objective: "dps_stripped_jungle_log", criteria: "minecraft.mined:minecraft.stripped_jungle_log", xp: 1 },
    { objective: "dps_stripped_acacia_log", criteria: "minecraft.mined:minecraft.stripped_acacia_log", xp: 1 },
    { objective: "dps_stripped_dark_oak_log", criteria: "minecraft.mined:minecraft.stripped_dark_oak_log", xp: 1 },
    { objective: "dps_stripped_mangrove_log", criteria: "minecraft.mined:minecraft.stripped_mangrove_log", xp: 1 },
    { objective: "dps_stripped_cherry_log", criteria: "minecraft.mined:minecraft.stripped_cherry_log", xp: 1 },
    { objective: "dps_oak_wood", criteria: "minecraft.mined:minecraft.oak_wood", xp: 1 },
    { objective: "dps_spruce_wood", criteria: "minecraft.mined:minecraft.spruce_wood", xp: 1 },
    { objective: "dps_birch_wood", criteria: "minecraft.mined:minecraft.birch_wood", xp: 1 },
    { objective: "dps_jungle_wood", criteria: "minecraft.mined:minecraft.jungle_wood", xp: 1 },
    { objective: "dps_acacia_wood", criteria: "minecraft.mined:minecraft.acacia_wood", xp: 1 },
    { objective: "dps_dark_oak_wood", criteria: "minecraft.mined:minecraft.dark_oak_wood", xp: 1 },
    { objective: "dps_mangrove_wood", criteria: "minecraft.mined:minecraft.mangrove_wood", xp: 1 },
    { objective: "dps_cherry_wood", criteria: "minecraft.mined:minecraft.cherry_wood", xp: 1 },
    { objective: "dps_stripped_oak_wood", criteria: "minecraft.mined:minecraft.stripped_oak_wood", xp: 1 },
    { objective: "dps_stripped_spruce_wood", criteria: "minecraft.mined:minecraft.stripped_spruce_wood", xp: 1 },
    { objective: "dps_stripped_birch_wood", criteria: "minecraft.mined:minecraft.stripped_birch_wood", xp: 1 },
    { objective: "dps_stripped_jungle_wood", criteria: "minecraft.mined:minecraft.stripped_jungle_wood", xp: 1 },
    { objective: "dps_stripped_acacia_wood", criteria: "minecraft.mined:minecraft.stripped_acacia_wood", xp: 1 },
    { objective: "dps_stripped_dark_oak_wood", criteria: "minecraft.mined:minecraft.stripped_dark_oak_wood", xp: 1 },
    { objective: "dps_stripped_mangrove_wood", criteria: "minecraft.mined:minecraft.stripped_mangrove_wood", xp: 1 },
    { objective: "dps_stripped_cherry_wood", criteria: "minecraft.mined:minecraft.stripped_cherry_wood", xp: 1 },
    { objective: "dps_oak_leaves", criteria: "minecraft.mined:minecraft.oak_leaves", xp: 1 },
    { objective: "dps_spruce_leaves", criteria: "minecraft.mined:minecraft.spruce_leaves", xp: 1 },
    { objective: "dps_birch_leaves", criteria: "minecraft.mined:minecraft.birch_leaves", xp: 1 },
    { objective: "dps_jungle_leaves", criteria: "minecraft.mined:minecraft.jungle_leaves", xp: 1 },
    { objective: "dps_acacia_leaves", criteria: "minecraft.mined:minecraft.acacia_leaves", xp: 1 },
    { objective: "dps_dark_oak_leaves", criteria: "minecraft.mined:minecraft.dark_oak_leaves", xp: 1 },
    { objective: "dps_mangrove_leaves", criteria: "minecraft.mined:minecraft.mangrove_leaves", xp: 1 },
    { objective: "dps_cherry_leaves", criteria: "minecraft.mined:minecraft.cherry_leaves", xp: 1 },
    { objective: "dps_crimson_stem", criteria: "minecraft.mined:minecraft.crimson_stem", xp: 2 },
    { objective: "dps_warped_stem", criteria: "minecraft.mined:minecraft.warped_stem", xp: 2 },
    { objective: "dps_stripped_crimson_stem", criteria: "minecraft.mined:minecraft.stripped_crimson_stem", xp: 2 },
    { objective: "dps_stripped_warped_stem", criteria: "minecraft.mined:minecraft.stripped_warped_stem", xp: 2 },
    { objective: "dps_crimson_hyphae", criteria: "minecraft.mined:minecraft.crimson_hyphae", xp: 2 },
    { objective: "dps_warped_hyphae", criteria: "minecraft.mined:minecraft.warped_hyphae", xp: 2 },
    { objective: "dps_stripped_crimson_hyphae", criteria: "minecraft.mined:minecraft.stripped_crimson_hyphae", xp: 2 },
    { objective: "dps_stripped_warped_hyphae", criteria: "minecraft.mined:minecraft.stripped_warped_hyphae", xp: 2 },
  ],
  farming: [
    { objective: "dps_wheat", criteria: "minecraft.mined:minecraft.wheat", xp: 1 },
    { objective: "dps_carrots", criteria: "minecraft.mined:minecraft.carrots", xp: 1 },
    { objective: "dps_potatoes", criteria: "minecraft.mined:minecraft.potatoes", xp: 1 },
    { objective: "dps_beetroots", criteria: "minecraft.mined:minecraft.beetroots", xp: 1 },
    { objective: "dps_sugar_cane", criteria: "minecraft.mined:minecraft.sugar_cane", xp: 1 },
    { objective: "dps_cocoa", criteria: "minecraft.mined:minecraft.cocoa", xp: 1 },
    { objective: "dps_bamboo", criteria: "minecraft.mined:minecraft.bamboo", xp: 1 },
    { objective: "dps_melon_stem", criteria: "minecraft.mined:minecraft.melon_stem", xp: 1 },
    { objective: "dps_pumpkin_stem", criteria: "minecraft.mined:minecraft.pumpkin_stem", xp: 1 },
    { objective: "dps_nether_wart", criteria: "minecraft.mined:minecraft.nether_wart", xp: 1 },
    { objective: "dps_sweet_berry_bush", criteria: "minecraft.mined:minecraft.sweet_berry_bush", xp: 1 },
    { objective: "dps_cactus", criteria: "minecraft.mined:minecraft.cactus", xp: 1 },
    { objective: "dps_mangrove_roots", criteria: "minecraft.mined:minecraft.mangrove_roots", xp: 1 },
    { objective: "dps_chorus_plant", criteria: "minecraft.mined:minecraft.chorus_plant", xp: 1 },
  ],
  enchanting: [
    { objective: "dps_enchanting_table", criteria: "minecraft.used:minecraft.enchanting_table", xp: 1 },
  ],
  fishing: [
    { objective: "dps_fish_caught", criteria: "minecraft.custom:minecraft.fish_caught", xp: 1 },
  ],
  archery: [
    { objective: "dps_bow", criteria: "minecraft.used:minecraft.bow", xp: 1 },
    { objective: "dps_crossbow", criteria: "minecraft.used:minecraft.crossbow", xp: 1 },
  ],
  taming: [
    { objective: "dps_animals_bred", criteria: "minecraft.custom:minecraft.animals_bred", xp: 3 },
  ],
  alchemy: [
    { objective: "dps_brewing_stand", criteria: "minecraft.custom:minecraft.interact_with_brewingstand", xp: 2 },
    { objective: "dps_potion_drunk", criteria: "minecraft.used:minecraft.potion", xp: 1 },
  ],
  acrobatics: [
    { objective: "dps_jumps", criteria: "minecraft.custom:minecraft.jump", xp: 1, divisor: 20 },
    { objective: "dps_fall_cm", criteria: "minecraft.custom:minecraft.fall_one_cm", xp: 1, divisor: 1000 },
  ],
  trading: [
    { objective: "dps_trades", criteria: "minecraft.custom:minecraft.traded_with_villager", xp: 2 },
  ],
} as const satisfies Record<string, readonly Action[]>;
