import type { ItemId } from "../../../mcgen/src/index.ts";
import { RECIPES } from "../../../mcgen/src/models/recipes.generated.ts";

// ---------------------------------------------------------------------------
// AOM registry
//
// Buildings, jobs and resources are declared once here. The build emits
// specialized functions per building type (hire/generation/render, sign
// text); nothing interprets jobs at runtime.
//
// Recipe ids are validated against the generated vanilla recipe list at
// module load, so a typo fails `bun run typecheck`/`bun run build` instead of
// silently producing an unlock that grants nothing.
// ---------------------------------------------------------------------------

const RECIPE_IDS = new Set<string>(RECIPES);

const GATED_RECIPES: string[] = [];

/** Marks a vanilla recipe id as gated and returns it. */
function r(id: string): string {
  GATED_RECIPES.push(id);
  return id;
}

function rList(...ids: string[]): string[] {
  return ids.map(r);
}

/** A plan recipe id (generated by this pack, not a vanilla recipe). */
export function planRecipe(id: string, wood: string): string {
  return `aom:plan/${id}/${wood}`;
}

const COLORS = [
  "white",
  "orange",
  "magenta",
  "light_blue",
  "yellow",
  "lime",
  "pink",
  "gray",
  "light_gray",
  "cyan",
  "purple",
  "blue",
  "brown",
  "green",
  "red",
  "black",
] as const;

export const WOODS = [
  { name: "oak", planks: "minecraft:oak_planks", sign: "minecraft:oak_sign" },
  { name: "spruce", planks: "minecraft:spruce_planks", sign: "minecraft:spruce_sign" },
  { name: "birch", planks: "minecraft:birch_planks", sign: "minecraft:birch_sign" },
  { name: "jungle", planks: "minecraft:jungle_planks", sign: "minecraft:jungle_sign" },
  { name: "acacia", planks: "minecraft:acacia_planks", sign: "minecraft:acacia_sign" },
  { name: "dark_oak", planks: "minecraft:dark_oak_planks", sign: "minecraft:dark_oak_sign" },
  { name: "mangrove", planks: "minecraft:mangrove_planks", sign: "minecraft:mangrove_sign" },
  { name: "cherry", planks: "minecraft:cherry_planks", sign: "minecraft:cherry_sign" },
  { name: "pale_oak", planks: "minecraft:pale_oak_planks", sign: "minecraft:pale_oak_sign" },
  { name: "poplar", planks: "minecraft:poplar_planks", sign: "minecraft:poplar_sign" },
  { name: "bamboo", planks: "minecraft:bamboo_planks", sign: "minecraft:bamboo_sign" },
  { name: "crimson", planks: "minecraft:crimson_planks", sign: "minecraft:crimson_sign" },
  { name: "warped", planks: "minecraft:warped_planks", sign: "minecraft:warped_sign" },
] as const;

const BOAT_WOODS = [
  "oak",
  "spruce",
  "birch",
  "jungle",
  "acacia",
  "dark_oak",
  "mangrove",
  "cherry",
  "pale_oak",
  "poplar",
] as const;

const OVERWORLD_WOODS = WOODS.filter((wood) => wood.name !== "crimson" && wood.name !== "warped");

function colored(suffix: string): string[] {
  return COLORS.map((color) => r(`minecraft:${color}${suffix}`));
}

function dyed(suffix: string): string[] {
  return COLORS.map((color) => r(`minecraft:dye_${color}${suffix}`));
}

// ---------------------------------------------------------------------------
// Resources
// ---------------------------------------------------------------------------

export interface Resource {
  readonly id: string;
  readonly label: string;
  readonly item: ItemId;
}

function res(id: string, label: string, item: ItemId): Resource {
  return { id, label, item };
}

export const RESOURCES: readonly Resource[] = [
  res("oak_logs", "Oak logs", "minecraft:oak_log"),
  res("spruce_logs", "Spruce logs", "minecraft:spruce_log"),
  res("birch_logs", "Birch logs", "minecraft:birch_log"),
  res("jungle_logs", "Jungle logs", "minecraft:jungle_log"),
  res("acacia_logs", "Acacia logs", "minecraft:acacia_log"),
  res("dark_oak_logs", "Dark oak logs", "minecraft:dark_oak_log"),
  res("mangrove_logs", "Mangrove logs", "minecraft:mangrove_log"),
  res("cherry_logs", "Cherry logs", "minecraft:cherry_log"),
  res("pale_oak_logs", "Pale oak logs", "minecraft:pale_oak_log"),

  res("coal", "Coal", "minecraft:coal"),
  res("raw_copper", "Raw copper", "minecraft:raw_copper"),
  res("raw_iron", "Raw iron", "minecraft:raw_iron"),
  res("redstone", "Redstone dust", "minecraft:redstone"),
  res("lapis_lazuli", "Lapis lazuli", "minecraft:lapis_lazuli"),
  res("raw_gold", "Raw gold", "minecraft:raw_gold"),
  res("diamond", "Diamond", "minecraft:diamond"),
  res("emerald", "Emerald", "minecraft:emerald"),

  res("gravel", "Gravel", "minecraft:gravel"),
  res("sand", "Sand", "minecraft:sand"),
  res("dirt", "Dirt", "minecraft:dirt"),
  res("cobblestone", "Cobblestone", "minecraft:cobblestone"),
  res("granite", "Granite", "minecraft:granite"),
  res("andesite", "Andesite", "minecraft:andesite"),
  res("diorite", "Diorite", "minecraft:diorite"),

  res("snow", "Snow", "minecraft:snow"),
  res("ice", "Ice", "minecraft:ice"),

  res("wheat", "Wheat", "minecraft:wheat"),
  res("carrot", "Carrot", "minecraft:carrot"),
  res("potato", "Potato", "minecraft:potato"),
  res("beetroot", "Beetroot", "minecraft:beetroot"),
  res("melon_slice", "Melon slice", "minecraft:melon_slice"),
  res("pumpkin", "Pumpkin", "minecraft:pumpkin"),
  res("sugar_cane", "Sugar cane", "minecraft:sugar_cane"),

  res("white_wool", "White wool", "minecraft:white_wool"),
  res("honeycomb", "Honeycomb", "minecraft:honeycomb"),

  res("raw_beef", "Raw beef", "minecraft:raw_beef"),
  res("porkchop", "Raw porkchop", "minecraft:porkchop"),
  res("chicken", "Raw chicken", "minecraft:chicken"),
  res("mutton", "Raw mutton", "minecraft:mutton"),
  res("rabbit", "Raw rabbit", "minecraft:rabbit"),

  res("cod", "Cod", "minecraft:cod"),
  res("salmon", "Salmon", "minecraft:salmon"),
  res("tropical_fish", "Tropical fish", "minecraft:tropical_fish"),
  res("pufferfish", "Pufferfish", "minecraft:pufferfish"),
];

export function resource(id: string): Resource {
  const found = RESOURCES.find((entry) => entry.id === id);
  if (!found) throw new Error(`Unknown resource: ${id}`);
  return found;
}

// ---------------------------------------------------------------------------
// Jobs and buildings
// ---------------------------------------------------------------------------

export interface TableEntry {
  /** Omitted for a "nothing" roll. */
  readonly resource?: string;
  readonly weight: number;
}

export type JobKind = "unlock" | "generation" | "storage" | "mechanic";

export interface Job {
  readonly id: string;
  readonly label: string;
  readonly kind: JobKind;
  /** Simple generation target. */
  readonly resource?: string;
  /** Weighted-generation table (mutually exclusive with `resource`). */
  readonly table?: readonly TableEntry[];
  /** Generation interval in minutes (1, 2, 5, 10 or 20; default 1). */
  readonly interval?: number;
  /** Storage capacity added per worker (default 576). */
  readonly capacity?: number;
  /** Unlock id this job activates. */
  readonly unlock?: string;
  /** Recipes a staffed unlock job grants. */
  readonly recipes?: readonly string[];
  /** Workers needed for an unlock to activate (default 1). */
  readonly required?: number;
  /** Special mechanic id. */
  readonly mechanic?: "leveller" | "portal" | "noop";
}

export type Category =
  | "Civic"
  | "Extraction"
  | "Industry"
  | "Agriculture"
  | "Husbandry"
  | "Food"
  | "Crafting"
  | "Knowledge"
  | "Special";

export interface BuildingType {
  readonly id: string;
  readonly label: string;
  readonly category: Category;
  readonly description: string;
  readonly townhall?: boolean;
  /** Contributes villagers to the town's population. */
  readonly population?: boolean;
  /** Unlock ids that must be staffed before the plan can be crafted. */
  readonly requires?: readonly string[];
  /** Plan ingredients besides the wood plank. */
  readonly planExtra: readonly ItemId[];
  readonly jobs: readonly Job[];
}

const LOGS = RESOURCES.filter((entry) => entry.id.endsWith("_logs"));
const ORES = [
  "coal",
  "raw_copper",
  "raw_iron",
  "redstone",
  "lapis_lazuli",
  "raw_gold",
  "diamond",
  "emerald",
].map(resource);
const QUARRY = [
  "gravel",
  "sand",
  "dirt",
  "cobblestone",
  "granite",
  "andesite",
  "diorite",
].map(resource);
const ICE = ["snow", "ice"].map(resource);
const CROPS = [
  "wheat",
  "carrot",
  "potato",
  "beetroot",
  "melon_slice",
  "pumpkin",
  "sugar_cane",
].map(resource);
const MEATS = ["raw_beef", "porkchop", "chicken", "mutton", "rabbit"].map(resource);
const FISH = ["cod", "salmon", "tropical_fish", "pufferfish"].map(resource);

const WINDMILL_IDS = [
  "windmill_wheat",
  "windmill_carrot",
  "windmill_potato",
  "windmill_beetroot",
  "windmill_melon",
  "windmill_pumpkin",
  "windmill_sugar_cane",
];

const WINDMILL_PLANS = WINDMILL_IDS.flatMap((id) =>
  WOODS.map((wood) => planRecipe(id, wood.name)),
);

const RECIPES_BY_BUILDING: Record<string, string[]> = {
  lumbermill: rList(
    "minecraft:crafting_table",
    "minecraft:wooden_axe",
    "minecraft:wooden_pickaxe",
    "minecraft:wooden_shovel",
    "minecraft:wooden_sword",
    "minecraft:wooden_spear",
  ),
  docks: rList(
    ...BOAT_WOODS.flatMap((wood) => [
      `minecraft:${wood}_boat`,
      `minecraft:${wood}_chest_boat`,
    ]),
    "minecraft:bamboo_raft",
    "minecraft:bamboo_chest_raft",
    "minecraft:conduit",
  ),
  ice_house: rList(
    "minecraft:snow_block",
    "minecraft:snow",
    "minecraft:packed_ice",
    "minecraft:blue_ice",
  ),
  stone_cutter: rList(
    "minecraft:cobblestone_stairs",
    "minecraft:cobblestone_slab",
    "minecraft:cobblestone_wall",
    "minecraft:stone_stairs",
    "minecraft:stone_slab",
    "minecraft:stone_bricks",
    "minecraft:stone_brick_stairs",
    "minecraft:stone_brick_slab",
    "minecraft:stone_brick_wall",
    "minecraft:chiseled_stone_bricks",
    "minecraft:cracked_stone_bricks",
    "minecraft:mossy_stone_bricks_from_vine",
    "minecraft:mossy_stone_bricks_from_moss_block",
    "minecraft:mossy_cobblestone_from_vine",
    "minecraft:mossy_cobblestone_from_moss_block",
    "minecraft:smooth_stone",
    "minecraft:smooth_stone_slab",
    "minecraft:furnace",
    "minecraft:stonecutter",
    "minecraft:stone_axe",
    "minecraft:stone_pickaxe",
    "minecraft:stone_shovel",
    "minecraft:stone_hoe",
    "minecraft:stone_sword",
    "minecraft:stone_spear",
  ),
  blacksmith: rList(
    "minecraft:iron_ingot_from_smelting_raw_iron",
    "minecraft:iron_ingot_from_blasting_raw_iron",
    "minecraft:iron_block",
    "minecraft:iron_bars",
    "minecraft:iron_door",
    "minecraft:iron_trapdoor",
    "minecraft:iron_chain",
    "minecraft:lantern",
    "minecraft:anvil",
    "minecraft:cauldron",
    "minecraft:hopper",
    "minecraft:compass",
    "minecraft:rail",
    "minecraft:minecart",
    "minecraft:chest_minecart",
    "minecraft:hopper_minecart",
    "minecraft:furnace_minecart",
    "minecraft:bucket",
    "minecraft:shears",
    "minecraft:saddle",
    "minecraft:flint_and_steel",
    "minecraft:shield",
    "minecraft:iron_helmet",
    "minecraft:iron_chestplate",
    "minecraft:iron_leggings",
    "minecraft:iron_boots",
    "minecraft:iron_axe",
    "minecraft:iron_pickaxe",
    "minecraft:iron_shovel",
    "minecraft:iron_hoe",
    "minecraft:iron_sword",
    "minecraft:iron_spear",
  ),
  gold_smith: rList(
    "minecraft:gold_ingot_from_smelting_raw_gold",
    "minecraft:gold_ingot_from_blasting_raw_gold",
    "minecraft:gold_block",
    "minecraft:gold_nugget",
    "minecraft:golden_apple",
    "minecraft:golden_carrot",
    "minecraft:glistering_melon_slice",
    "minecraft:golden_helmet",
    "minecraft:golden_chestplate",
    "minecraft:golden_leggings",
    "minecraft:golden_boots",
    "minecraft:golden_axe",
    "minecraft:golden_pickaxe",
    "minecraft:golden_shovel",
    "minecraft:golden_hoe",
    "minecraft:golden_sword",
    "minecraft:golden_spear",
    "minecraft:clock",
    "minecraft:powered_rail",
    "minecraft:light_weighted_pressure_plate",
    "minecraft:blast_furnace",
  ),
  jeweller_diamond: rList(
    "minecraft:diamond_block",
    "minecraft:diamond_helmet",
    "minecraft:diamond_chestplate",
    "minecraft:diamond_leggings",
    "minecraft:diamond_boots",
    "minecraft:diamond_axe",
    "minecraft:diamond_pickaxe",
    "minecraft:diamond_shovel",
    "minecraft:diamond_hoe",
    "minecraft:diamond_sword",
    "minecraft:diamond_spear",
    "minecraft:enchanting_table",
    "minecraft:jukebox",
    "minecraft:lodestone",
    "minecraft:recovery_compass",
  ),
  jeweller_netherite: rList(
    "minecraft:netherite_ingot",
    "minecraft:netherite_block",
    "minecraft:netherite_helmet_smithing",
    "minecraft:netherite_chestplate_smithing",
    "minecraft:netherite_leggings_smithing",
    "minecraft:netherite_boots_smithing",
    "minecraft:netherite_axe_smithing",
    "minecraft:netherite_pickaxe_smithing",
    "minecraft:netherite_shovel_smithing",
    "minecraft:netherite_hoe_smithing",
    "minecraft:netherite_sword_smithing",
    "minecraft:netherite_spear_smithing",
    "minecraft:netherite_upgrade_smithing_template",
  ),
  coppersmith: rList(
    "minecraft:copper_block",
    "minecraft:cut_copper",
    "minecraft:cut_copper_stairs",
    "minecraft:cut_copper_slab",
    "minecraft:chiseled_copper",
    "minecraft:copper_grate",
    "minecraft:copper_bulb",
    "minecraft:copper_door",
    "minecraft:copper_trapdoor",
    "minecraft:lightning_rod",
    "minecraft:spyglass",
    "minecraft:copper_spear",
    ...RECIPES.filter((recipe) => recipe.startsWith("minecraft:waxed_")),
  ),
  kiln: rList(
    "minecraft:bricks",
    "minecraft:brick_stairs",
    "minecraft:brick_slab",
    "minecraft:brick_wall",
    "minecraft:terracotta",
    ...colored("_glazed_terracotta"),
    "minecraft:flower_pot",
    "minecraft:decorated_pot",
    ...colored("_concrete_powder"),
  ),
  masons_yard: rList(
    "minecraft:cobbled_deepslate_stairs",
    "minecraft:cobbled_deepslate_slab",
    "minecraft:cobbled_deepslate_wall",
    "minecraft:polished_deepslate",
    "minecraft:polished_deepslate_stairs",
    "minecraft:polished_deepslate_slab",
    "minecraft:polished_deepslate_wall",
    "minecraft:deepslate_bricks",
    "minecraft:deepslate_brick_stairs",
    "minecraft:deepslate_brick_slab",
    "minecraft:deepslate_brick_wall",
    "minecraft:deepslate_tiles",
    "minecraft:deepslate_tile_stairs",
    "minecraft:deepslate_tile_slab",
    "minecraft:deepslate_tile_wall",
    "minecraft:chiseled_deepslate",
    "minecraft:cracked_deepslate_bricks",
    "minecraft:cracked_deepslate_tiles",
    "minecraft:polished_tuff",
    "minecraft:tuff_bricks",
    "minecraft:chiseled_tuff",
    "minecraft:tuff_stairs",
    "minecraft:tuff_slab",
    "minecraft:tuff_wall",
    "minecraft:dripstone_block",
    "minecraft:packed_mud",
    "minecraft:mud_bricks",
    "minecraft:mud_brick_stairs",
    "minecraft:mud_brick_slab",
    "minecraft:mud_brick_wall",
  ),
  farmer: rList(
    "minecraft:bucket",
    "minecraft:wooden_hoe",
    "minecraft:stone_hoe",
    "minecraft:iron_hoe",
    "minecraft:golden_hoe",
    "minecraft:diamond_hoe",
    "minecraft:netherite_hoe_smithing",
  ),
  herder: rList("minecraft:lead", "minecraft:saddle"),
  tanner: rList(
    "minecraft:leather_helmet",
    "minecraft:leather_chestplate",
    "minecraft:leather_leggings",
    "minecraft:leather_boots",
    "minecraft:leather_horse_armor",
    "minecraft:item_frame",
    "minecraft:glow_item_frame",
    "minecraft:book",
    "minecraft:bundle",
    "minecraft:saddle",
  ),
  shepherd: rList("minecraft:shears", "minecraft:lead"),
  spinner: rList(
    "minecraft:white_wool_from_string",
    ...dyed("_wool"),
    ...colored("_carpet"),
    ...dyed("_carpet"),
    ...colored("_bed"),
    ...dyed("_bed"),
    "minecraft:straw_bed",
    "minecraft:lead",
    "minecraft:bundle",
  ),
  weaver: rList(
    "minecraft:loom",
    ...colored("_banner"),
    ...colored("_banner_duplicate"),
    "minecraft:bordure_indented_banner_pattern",
    "minecraft:creeper_banner_pattern",
    "minecraft:field_masoned_banner_pattern",
    "minecraft:flower_banner_pattern",
    "minecraft:mojang_banner_pattern",
    "minecraft:skull_banner_pattern",
    "minecraft:shield",
    ...colored("_bed"),
    ...dyed("_bed"),
    "minecraft:straw_bed",
  ),
  beekeeper: rList(
    "minecraft:beehive",
    "minecraft:honeycomb_block",
    "minecraft:honey_block",
    "minecraft:candle",
    ...colored("_candle"),
    ...RECIPES.filter((recipe) => recipe.startsWith("minecraft:waxed_")),
  ),
  baker: rList(
    "minecraft:baked_potato",
    "minecraft:golden_carrot",
    "minecraft:cake",
    "minecraft:cookie",
  ),
  butcher: rList("minecraft:smoker"),
  brewer: rList(
    "minecraft:glass_bottle",
    "minecraft:brewing_stand",
    "minecraft:blaze_powder",
    "minecraft:fermented_spider_eye",
    "minecraft:magma_cream",
    "minecraft:glistering_melon_slice",
    "minecraft:cauldron",
  ),
  fisher: rList(
    "minecraft:fishing_rod",
    "minecraft:carrot_on_a_stick",
    "minecraft:warped_fungus_on_a_stick",
  ),
  weapon_smith: rList(
    "minecraft:wooden_sword",
    "minecraft:wooden_spear",
    "minecraft:stone_sword",
    "minecraft:stone_spear",
    "minecraft:iron_sword",
    "minecraft:iron_spear",
    "minecraft:golden_sword",
    "minecraft:golden_spear",
    "minecraft:copper_sword",
    "minecraft:copper_spear",
    "minecraft:diamond_sword",
    "minecraft:diamond_spear",
    "minecraft:netherite_sword_smithing",
    "minecraft:netherite_spear_smithing",
  ),
  fletcher: rList(
    "minecraft:bow",
    "minecraft:crossbow",
    "minecraft:arrow",
    "minecraft:spectral_arrow",
    "minecraft:tipped_arrow",
    "minecraft:fletching_table",
    "minecraft:target",
  ),
  glass_blower: rList(
    "minecraft:glass",
    "minecraft:glass_pane",
    ...colored("_stained_glass"),
    ...colored("_stained_glass_pane"),
    ...COLORS.map((color) => r(`minecraft:${color}_stained_glass_pane_from_glass_pane`)),
    "minecraft:daylight_detector",
    "minecraft:beacon",
    "minecraft:end_crystal",
  ),
  painter: rList("minecraft:painting"),
  tinkerer: rList(
    "minecraft:piston",
    "minecraft:sticky_piston",
    "minecraft:observer",
    "minecraft:repeater",
    "minecraft:comparator",
    "minecraft:redstone_torch",
    "minecraft:dispenser",
    "minecraft:dropper",
    "minecraft:hopper",
    "minecraft:redstone_lamp",
    "minecraft:note_block",
    "minecraft:target",
    "minecraft:lever",
    ...WOODS.map((wood) => r(`minecraft:${wood.name}_button`)),
    "minecraft:stone_button",
    "minecraft:polished_blackstone_button",
    ...WOODS.map((wood) => r(`minecraft:${wood.name}_pressure_plate`)),
    "minecraft:stone_pressure_plate",
    "minecraft:light_weighted_pressure_plate",
    "minecraft:heavy_weighted_pressure_plate",
    "minecraft:polished_blackstone_pressure_plate",
    "minecraft:tripwire_hook",
    "minecraft:daylight_detector",
    "minecraft:tnt",
  ),
  bard: rList("minecraft:jukebox", "minecraft:note_block"),
  armorer: rList(
    "minecraft:smithing_table",
    "minecraft:grindstone",
    "minecraft:armor_stand",
    "minecraft:anvil",
    "minecraft:iron_helmet",
    "minecraft:iron_chestplate",
    "minecraft:iron_leggings",
    "minecraft:iron_boots",
    ...RECIPES.filter((recipe) =>
      recipe.endsWith("_armor_trim_smithing_template_smithing_trim"),
    ),
  ),
  librarian: rList(
    "minecraft:book",
    "minecraft:writable_book",
    "minecraft:bookshelf",
    "minecraft:chiseled_bookshelf",
    "minecraft:lectern",
  ),
  enchanter: rList("minecraft:enchanting_table"),
  teacher: rList("minecraft:flint_and_steel"),
  firekeeper: rList("minecraft:fire_charge", "minecraft:ender_chest"),
  cartographer: rList(
    "minecraft:cartography_table",
    "minecraft:map",
    "minecraft:map_cloning",
    "minecraft:map_extending",
    "minecraft:recovery_compass",
    "minecraft:lodestone",
    "minecraft:spyglass",
    "minecraft:item_frame",
    "minecraft:glow_item_frame",
  ),
  astronomer: rList(
    "minecraft:purpur_block",
    "minecraft:purpur_pillar",
    "minecraft:purpur_stairs",
    "minecraft:purpur_slab",
    "minecraft:end_stone_bricks",
    "minecraft:end_stone_brick_stairs",
    "minecraft:end_stone_brick_slab",
    "minecraft:end_stone_brick_wall",
    "minecraft:end_rod",
    "minecraft:ender_chest",
    "minecraft:ender_eye",
    "minecraft:shulker_box",
    ...colored("_shulker_box"),
    "minecraft:end_crystal",
    "minecraft:beacon",
  ),
};

function unlock(
  id: string,
  label: string,
  recipes: readonly string[],
  required = 1,
): Job {
  return { id, label, kind: "unlock", unlock: id, recipes, required };
}

function generator(
  id: string,
  label: string,
  resource: string,
  interval = 1,
): Job {
  return { id, label, kind: "generation", resource, interval };
}

function banker(id: string, label: string, resource: string): Job {
  return { id, label, kind: "storage", resource, capacity: 576 };
}

function chopper(wood: Resource): Job[] {
  return [
    generator(`${wood.id}_cutter`, `${wood.label} chopper`, wood.id),
    banker(`${wood.id}_banker`, `${wood.label} banker`, wood.id),
  ];
}

function digger(wood: Resource): Job[] {
  return [
    generator(`${wood.id}_digger`, `${wood.label} digger`, wood.id),
    banker(`${wood.id}_banker`, `${wood.label} banker`, wood.id),
  ];
}

function windmill(
  id: string,
  label: string,
  crop: string,
  planExtra: ItemId,
): BuildingType {
  const res = resource(crop);
  return {
    id,
    label,
    category: "Agriculture",
    description: `Farms and stores ${res.label.toLowerCase()}.`,
    requires: ["farmer"],
    planExtra: [planExtra],
    jobs: chopper(res),
  };
}

export const BUILDINGS: readonly BuildingType[] = [
  {
    id: "townhall",
    label: "Townhall",
    category: "Civic",
    description: "Anchors the town and manages its membership.",
    townhall: true,
    planExtra: ["minecraft:oak_sapling"],
    jobs: [],
  },
  {
    id: "townhouse",
    label: "Townhouse",
    category: "Civic",
    description: "Houses villagers for the town.",
    population: true,
    planExtra: [],
    jobs: [],
  },
  {
    id: "lumbermill",
    label: "Lumbermill",
    category: "Extraction",
    description: "Generates and stores wood; unlocks wooden tool recipes.",
    planExtra: ["minecraft:oak_log"],
    jobs: [
      unlock("tool_crafter", "Tool crafter", RECIPES_BY_BUILDING.lumbermill!),
      ...LOGS.flatMap(chopper),
    ],
  },
  {
    id: "mine",
    label: "Mine",
    category: "Extraction",
    description: "Lets the town dig deeper and produces raw ores.",
    planExtra: ["minecraft:wooden_pickaxe"],
    jobs: [
      { id: "leveller", label: "Leveller", kind: "mechanic", mechanic: "leveller" },
      {
        id: "miner",
        label: "Miner",
        kind: "generation",
        interval: 1,
        table: [
          { resource: "coal", weight: 300 },
          { resource: "raw_copper", weight: 250 },
          { resource: "raw_iron", weight: 200 },
          { resource: "redstone", weight: 100 },
          { resource: "lapis_lazuli", weight: 70 },
          { resource: "raw_gold", weight: 50 },
          { resource: "diamond", weight: 5 },
          { resource: "emerald", weight: 2 },
          { weight: 23 },
        ],
      },
      ...ORES.map((res) => banker(`${res.id}_miner`, `${res.label} miner`, res.id)),
    ],
  },
  {
    id: "quarry",
    label: "Quarry",
    category: "Extraction",
    description: "Digs up stone and soil in bulk.",
    planExtra: ["minecraft:gravel"],
    jobs: QUARRY.flatMap(digger),
  },
  {
    id: "docks",
    label: "Docks",
    category: "Extraction",
    description: "Builds boats and rafts.",
    planExtra: ["minecraft:wooden_shovel"],
    jobs: [unlock("shipwright", "Shipwright", RECIPES_BY_BUILDING.docks!)],
  },
  {
    id: "ice_house",
    label: "Ice House",
    category: "Extraction",
    description: "Harvests and stores ice and snow.",
    planExtra: ["minecraft:snowball"],
    jobs: [
      unlock("icer", "Icer", RECIPES_BY_BUILDING.ice_house!),
      generator("snow_harvester", "Snow harvester", "snow"),
      generator("ice_harvester", "Ice harvester", "ice"),
      banker("snow_banker", "Snow banker", "snow"),
      banker("ice_banker", "Ice banker", "ice"),
    ],
  },
  {
    id: "stone_cutter",
    label: "Stone cutter",
    category: "Industry",
    description: "Unlocks cobblestone and stone recipes.",
    planExtra: ["minecraft:cobblestone"],
    jobs: [unlock("stone_cutter", "Stone cutter", RECIPES_BY_BUILDING.stone_cutter!)],
  },
  {
    id: "blacksmith",
    label: "Blacksmith",
    category: "Industry",
    description: "Unlocks iron recipes.",
    planExtra: ["minecraft:raw_iron"],
    jobs: [unlock("blacksmith", "Blacksmith", RECIPES_BY_BUILDING.blacksmith!)],
  },
  {
    id: "gold_smith",
    label: "Gold smith",
    category: "Industry",
    description: "Unlocks gold recipes.",
    requires: ["coppersmith"],
    planExtra: ["minecraft:raw_gold"],
    jobs: [unlock("gold_smith", "Gold smith", RECIPES_BY_BUILDING.gold_smith!)],
  },
  {
    id: "jeweller",
    label: "Jeweller",
    category: "Industry",
    description: "Unlocks diamond and netherite recipes.",
    requires: ["gold_smith"],
    planExtra: ["minecraft:diamond"],
    jobs: [
      unlock("jeweller_diamond", "Jewellers", RECIPES_BY_BUILDING.jeweller_diamond!, 2),
      unlock("jeweller_netherite", "Master jewellers", RECIPES_BY_BUILDING.jeweller_netherite!, 5),
    ],
  },
  {
    id: "coppersmith",
    label: "Coppersmith",
    category: "Industry",
    description: "Works copper into blocks, bulbs and lenses.",
    requires: ["blacksmith"],
    planExtra: ["minecraft:raw_copper"],
    jobs: [unlock("coppersmith", "Coppersmith", RECIPES_BY_BUILDING.coppersmith!)],
  },
  {
    id: "kiln",
    label: "Kiln",
    category: "Industry",
    description: "Bakes clay and dyes into bricks, pots and concrete.",
    planExtra: ["minecraft:clay_ball"],
    jobs: [unlock("potter", "Potter", RECIPES_BY_BUILDING.kiln!)],
  },
  {
    id: "masons_yard",
    label: "Mason's Yard",
    category: "Industry",
    description: "Cuts the deep rock: deepslate, tuff and mud.",
    planExtra: ["minecraft:deepslate"],
    jobs: [unlock("mason", "Mason", RECIPES_BY_BUILDING.masons_yard!)],
  },
  {
    id: "farm",
    label: "Farm",
    category: "Agriculture",
    description: "Unlocks farming recipes and windmill plans.",
    planExtra: ["minecraft:dirt"],
    jobs: [
      unlock("farmer", "Farmer", [
        ...RECIPES_BY_BUILDING.farmer!,
        ...WINDMILL_PLANS,
      ]),
    ],
  },
  windmill("windmill_wheat", "Wheat windmill", "wheat", "minecraft:wheat"),
  windmill("windmill_carrot", "Carrot windmill", "carrot", "minecraft:carrot"),
  windmill("windmill_potato", "Potato windmill", "potato", "minecraft:potato"),
  windmill("windmill_beetroot", "Beetroot windmill", "beetroot", "minecraft:beetroot_seeds"),
  windmill("windmill_melon", "Melon windmill", "melon_slice", "minecraft:melon_seeds"),
  windmill("windmill_pumpkin", "Pumpkin windmill", "pumpkin", "minecraft:pumpkin"),
  windmill("windmill_sugar_cane", "Sugar cane windmill", "sugar_cane", "minecraft:sugar_cane"),
  {
    id: "barn",
    label: "Barn",
    category: "Husbandry",
    description: "Feeds the town's animals.",
    planExtra: ["minecraft:hay_block"],
    jobs: [unlock("herder", "Herder", RECIPES_BY_BUILDING.herder!)],
  },
  {
    id: "leather_tanner",
    label: "Leather tanner",
    category: "Husbandry",
    description: "Unlocks leather recipes.",
    planExtra: ["minecraft:leather"],
    jobs: [unlock("tanner", "Tanner", RECIPES_BY_BUILDING.tanner!)],
  },
  {
    id: "shepherd",
    label: "Shepherd",
    category: "Husbandry",
    description: "Keeps track of sheep.",
    planExtra: ["minecraft:mutton"],
    jobs: [
      unlock("shepherd", "Shepherd", RECIPES_BY_BUILDING.shepherd!),
      generator("shearer", "Shearer", "white_wool", 2),
      banker("wool_banker", "Wool banker", "white_wool"),
    ],
  },
  {
    id: "spinnery",
    label: "Spinnery",
    category: "Husbandry",
    description: "Spins wool and string into other materials.",
    planExtra: ["minecraft:string"],
    jobs: [unlock("spinner", "Spinner", RECIPES_BY_BUILDING.spinner!)],
  },
  {
    id: "weaver",
    label: "Weaver",
    category: "Husbandry",
    description: "Weaves banners, patterns and beds.",
    planExtra: ["minecraft:white_wool"],
    jobs: [unlock("weaver", "Weaver", RECIPES_BY_BUILDING.weaver!)],
  },
  {
    id: "apiary",
    label: "Apiary",
    category: "Husbandry",
    description: "Keeps bees and harvests honey and wax.",
    planExtra: ["minecraft:honeycomb"],
    jobs: [
      unlock("beekeeper", "Beekeeper", RECIPES_BY_BUILDING.beekeeper!),
      generator("honey_harvester", "Honey harvester", "honeycomb", 5),
      banker("honeycomb_banker", "Honeycomb banker", "honeycomb"),
    ],
  },
  {
    id: "baker",
    label: "Baker",
    category: "Food",
    description: "Unlocks baked recipes.",
    planExtra: ["minecraft:furnace"],
    jobs: [unlock("baker", "Baker", RECIPES_BY_BUILDING.baker!)],
  },
  {
    id: "butcher",
    label: "Butcher",
    category: "Food",
    description: "Butchers animals for meat.",
    planExtra: ["minecraft:wooden_sword"],
    jobs: [
      unlock("butcher", "Butcher", RECIPES_BY_BUILDING.butcher!),
      {
        id: "meat_cutter",
        label: "Butcher",
        kind: "generation",
        interval: 2,
        table: MEATS.map((res) => ({ resource: res.id, weight: 1 })),
      },
      ...MEATS.map((res) => banker(`${res.id}_banker`, `${res.label} banker`, res.id)),
    ],
  },
  {
    id: "brewery",
    label: "Brewery",
    category: "Food",
    description: "Unlocks brewing recipes.",
    planExtra: ["minecraft:nether_wart"],
    jobs: [unlock("brewer", "Brewer", RECIPES_BY_BUILDING.brewer!)],
  },
  {
    id: "fisher",
    label: "Fisher",
    category: "Food",
    description: "Fishes for the town.",
    planExtra: ["minecraft:cod"],
    jobs: [
      unlock("fisher", "Fisher", RECIPES_BY_BUILDING.fisher!),
      {
        id: "coastal_fisher",
        label: "Coastal fisher",
        kind: "generation",
        interval: 2,
        table: [
          { resource: "cod", weight: 1 },
          { resource: "salmon", weight: 1 },
        ],
      },
      {
        id: "deep_fisher",
        label: "Deep fisher",
        kind: "generation",
        interval: 10,
        table: [
          { resource: "tropical_fish", weight: 1 },
          { resource: "pufferfish", weight: 1 },
        ],
      },
      ...FISH.map((res) => banker(`${res.id}_banker`, `${res.label} banker`, res.id)),
    ],
  },
  {
    id: "weapon_smith",
    label: "Weapon smith",
    category: "Crafting",
    description: "Unlocks swords and spears.",
    planExtra: ["minecraft:wooden_axe"],
    jobs: [unlock("weapon_smith", "Weapon smith", RECIPES_BY_BUILDING.weapon_smith!)],
  },
  {
    id: "fletcher",
    label: "Fletcher",
    category: "Crafting",
    description: "Unlocks ranged weapons.",
    planExtra: ["minecraft:feather"],
    jobs: [unlock("fletcher", "Fletcher", RECIPES_BY_BUILDING.fletcher!)],
  },
  {
    id: "glass_blower",
    label: "Glass blower",
    category: "Crafting",
    description: "Unlocks glass recipes.",
    planExtra: ["minecraft:sand"],
    jobs: [unlock("glass_blower", "Glass blower", RECIPES_BY_BUILDING.glass_blower!)],
  },
  {
    id: "painter",
    label: "Painter",
    category: "Crafting",
    description: "Unlocks paintings.",
    planExtra: ["minecraft:ink_sac"],
    jobs: [unlock("painter", "Painter", RECIPES_BY_BUILDING.painter!)],
  },
  {
    id: "redstone_workshop",
    label: "Redstone Workshop",
    category: "Crafting",
    description: "Unlocks redstone recipes.",
    planExtra: ["minecraft:redstone"],
    jobs: [unlock("tinkerer", "Tinkerer", RECIPES_BY_BUILDING.tinkerer!)],
  },
  {
    id: "bard",
    label: "Bard",
    category: "Crafting",
    description: "Unlocks music recipes.",
    planExtra: ["minecraft:goat_horn"],
    jobs: [unlock("bard", "Bard", RECIPES_BY_BUILDING.bard!)],
  },
  {
    id: "armory",
    label: "Armory",
    category: "Crafting",
    description: "Fits the town's guards with armor.",
    planExtra: ["minecraft:iron_ingot"],
    jobs: [unlock("armorer", "Armorer", RECIPES_BY_BUILDING.armorer!)],
  },
  {
    id: "library",
    label: "Library",
    category: "Knowledge",
    description: "Stores books and unlocks enchanting.",
    planExtra: ["minecraft:paper"],
    jobs: [
      unlock("librarian", "Librarian", RECIPES_BY_BUILDING.librarian!),
      unlock("enchanter", "Enchanter", RECIPES_BY_BUILDING.enchanter!),
    ],
  },
  {
    id: "school",
    label: "School",
    category: "Knowledge",
    description: "Teaches the town's basics.",
    requires: ["librarian"],
    planExtra: ["minecraft:bookshelf"],
    jobs: [unlock("teacher", "Teacher", RECIPES_BY_BUILDING.teacher!)],
  },
  {
    id: "university",
    label: "University",
    category: "Knowledge",
    description: "Researches technologies, including Nether travel.",
    requires: ["teacher"],
    planExtra: ["minecraft:obsidian"],
    jobs: [
      unlock("firekeeper", "Firekeeper", RECIPES_BY_BUILDING.firekeeper!),
      { id: "portal", label: "Portal", kind: "mechanic", mechanic: "portal" },
    ],
  },
  {
    id: "cartographers_guild",
    label: "Cartographer's Guild",
    category: "Knowledge",
    description: "Maps the land and places lodestones.",
    planExtra: ["minecraft:compass"],
    jobs: [unlock("cartographer", "Cartographer", RECIPES_BY_BUILDING.cartographer!)],
  },
  {
    id: "end_observatory",
    label: "End Observatory",
    category: "Knowledge",
    description: "Studies the End and stores its materials.",
    planExtra: ["minecraft:end_stone"],
    jobs: [unlock("astronomer", "Astronomer", RECIPES_BY_BUILDING.astronomer!)],
  },
  {
    id: "custom",
    label: "Custom",
    category: "Special",
    description: "A blank building for whatever the town needs.",
    population: true,
    planExtra: ["minecraft:stick"],
    jobs: [{ id: "hire", label: "Hired help", kind: "mechanic", mechanic: "noop" }],
  },
];

// ---------------------------------------------------------------------------
// Derived helpers
// ---------------------------------------------------------------------------

export const SPECIAL_BUILDINGS = BUILDINGS.filter(
  (building) => building.townhall || building.population,
);

export const INDUSTRIAL_BUILDINGS = BUILDINGS.filter(
  (building) => !building.townhall,
);

export const BUILD_MENU_BUILDINGS = BUILDINGS;

export const CATEGORIES: readonly Category[] = [
  "Civic",
  "Extraction",
  "Industry",
  "Agriculture",
  "Husbandry",
  "Food",
  "Crafting",
  "Knowledge",
  "Special",
];

export function buildingType(id: string): BuildingType {
  const found = BUILDINGS.find((entry) => entry.id === id);
  if (!found) throw new Error(`Unknown building: ${id}`);
  return found;
}

/** The storage resources a building uses, in registry order. */
export function buildingResources(type: BuildingType): Resource[] {
  const ids: string[] = [];
  for (const job of type.jobs) {
    if (job.kind === "storage" && job.resource && !ids.includes(job.resource)) {
      ids.push(job.resource);
    }
    for (const entry of job.table ?? []) {
      if (entry.resource && !ids.includes(entry.resource)) ids.push(entry.resource);
    }
  }
  return ids.map(resource);
}

/** The generation jobs producing a resource. */
export function generationJobs(
  type: BuildingType,
  resourceId: string,
): Job[] {
  return type.jobs.filter((job) => {
    if (job.kind !== "generation") return false;
    if (job.resource === resourceId) return true;
    return job.table?.some((entry) => entry.resource === resourceId) ?? false;
  });
}

/** The storage jobs expanding a resource's capacity. */
export function storageJobs(type: BuildingType, resourceId: string): Job[] {
  return type.jobs.filter(
    (job) => job.kind === "storage" && job.resource === resourceId,
  );
}

export function mechanicJobs(type: BuildingType, mechanic: Job["mechanic"]): Job[] {
  return type.jobs.filter((job) => job.kind === "mechanic" && job.mechanic === mechanic);
}

export function unlockJobs(type: BuildingType): Job[] {
  return type.jobs.filter((job) => job.kind === "unlock");
}

/** Unlock id -> recipes granted while it is active. */
export function unlockRecipes(): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const building of BUILDINGS) {
    for (const job of building.jobs) {
      if (job.kind !== "unlock" || !job.unlock) continue;
      const recipes = map.get(job.unlock) ?? [];
      recipes.push(...(job.recipes ?? []));
      map.set(job.unlock, recipes);
    }
  }
  return map;
}

export interface UnlockInfo {
  readonly id: string;
  readonly label: string;
  readonly required: number;
}

/** Unlock id -> activation requirement (max needed across jobs). */
export function unlocks(): Map<string, UnlockInfo> {
  const map = new Map<string, UnlockInfo>();
  for (const building of BUILDINGS) {
    for (const job of building.jobs) {
      if (job.kind !== "unlock" || !job.unlock) continue;
      const required = job.required ?? 1;
      const existing = map.get(job.unlock);
      if (!existing || required > existing.required) {
        map.set(job.unlock, { id: job.unlock, label: job.label, required });
      }
    }
  }
  return map;
}

/**
 * Recipe -> the unlock ids that must all be active for it to be granted.
 * Recipes listed under several buildings require every one of them, matching
 * the design's `(also ...)` appendix.
 */
export function recipeRequirements(): Map<string, string[]> {
  const map = new Map<string, Set<string>>();
  for (const building of BUILDINGS) {
    for (const job of building.jobs) {
      if (job.kind !== "unlock" || !job.unlock) continue;
      for (const recipe of job.recipes ?? []) {
        const owners = map.get(recipe) ?? new Set<string>();
        owners.add(job.unlock);
        map.set(recipe, owners);
      }
    }
    // Plan recipes are gated by the building's `requires` list.
    for (const wood of WOODS) {
      const recipe = planRecipe(building.id, wood.name);
      const owners = map.get(recipe) ?? new Set<string>();
      for (const unlockId of building.requires ?? []) owners.add(unlockId);
      map.set(recipe, owners);
    }
  }
  const result = new Map<string, string[]>();
  for (const [recipe, owners] of map) result.set(recipe, [...owners]);
  return result;
}

/** Every recipe this pack gates (vanilla unlocks plus generated plans). */
export function gatedRecipes(): string[] {
  return [...recipeRequirements().keys()];
}

/** Plan ingredients (the wood plank is added per wood type by the build). */
export function planExtras(type: BuildingType): readonly ItemId[] {
  return type.planExtra;
}

// ---------------------------------------------------------------------------
// Action indices
// ---------------------------------------------------------------------------

export const TOWNHALL_ACTIONS = {
  join: 1,
  leave: 2,
  deleteTown: 3,
  pagePrev: 10,
  pageNext: 11,
} as const;

export const POPULATION_ACTIONS = {
  addVillager: 1,
  removeVillager: 2,
  delete: 3,
} as const;

export const CONFIRM_ACTION = -1;

export const STORAGE_AMOUNTS = [
  { value: 1, label: "1" },
  { value: 16, label: "16" },
  { value: 64, label: "64" },
  { value: 2147483647, label: "all" },
] as const;

/** First `aom.action` index used by a building's storage buttons. */
function actionBase(type: BuildingType): number {
  return type.jobs.length + (type.population ? 2 : 0) + 1;
}

/** `aom.action` index of the population Add/Remove villager buttons. */
export function populationAction(
  type: BuildingType,
  kind: "add" | "remove",
): number {
  return type.jobs.length + (kind === "add" ? 1 : 2);
}

/** `aom.action` index for a deposit/withdraw button. */
export function storageAction(
  type: BuildingType,
  resourceIndex: number,
  kind: "deposit" | "withdraw",
  amountIndex: number,
): number {
  const base = actionBase(type);
  return base + resourceIndex * (STORAGE_AMOUNTS.length * 2) +
    (kind === "deposit" ? 0 : STORAGE_AMOUNTS.length) + amountIndex;
}

/** `aom.action` index of the delete-building button. */
export function deleteAction(type: BuildingType): number {
  return actionBase(type) +
    buildingResources(type).length * STORAGE_AMOUNTS.length * 2;
}

/** Validates every gated vanilla recipe id against the generated model. */
const unknown = [...new Set(GATED_RECIPES)].filter(
  (id) => id.startsWith("minecraft:") && !RECIPE_IDS.has(id),
);
if (unknown.length) {
  throw new Error(
    `Unknown vanilla recipes:\n${unknown.sort().join("\n")}`,
  );
}
