// AUTO-GENERATED by tools/build-techdemo.ts from packs/aom/DESIGN.md.
// Do not edit by hand — run `bun tools/build-techdemo.ts` to regenerate.

import { Datapack, latestVersion } from "../../../mcgen/src/index.ts";

const BACKGROUND = "minecraft:block/deepslate_tiles";

interface Node {
  readonly id: string;
  readonly parent: string | null;
  readonly icon: string;
  readonly title: string;
  readonly description: string;
  readonly frame: "task" | "goal" | "challenge";
}

const NODES: readonly Node[] = [
  {
    "id": "root",
    "parent": null,
    "icon": "minecraft:grass_block",
    "title": "Age of Minecraft",
    "description": "Age of Minecraft building tech tree preview. Every node is granted for testing.",
    "frame": "goal"
  },
  {
    "id": "cat_civic",
    "parent": "root",
    "icon": "minecraft:bell",
    "title": "Civic",
    "description": "The Civic branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "cat_extraction",
    "parent": "root",
    "icon": "minecraft:iron_pickaxe",
    "title": "Extraction",
    "description": "The Extraction branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "cat_industry",
    "parent": "root",
    "icon": "minecraft:anvil",
    "title": "Industry",
    "description": "The Industry branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "cat_agriculture",
    "parent": "root",
    "icon": "minecraft:wheat",
    "title": "Agriculture",
    "description": "The Agriculture branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "cat_husbandry",
    "parent": "root",
    "icon": "minecraft:white_wool",
    "title": "Husbandry",
    "description": "The Husbandry branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "cat_food",
    "parent": "root",
    "icon": "minecraft:cooked_beef",
    "title": "Food",
    "description": "The Food branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "cat_crafting",
    "parent": "root",
    "icon": "minecraft:crafting_table",
    "title": "Crafting",
    "description": "The Crafting branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "cat_knowledge",
    "parent": "root",
    "icon": "minecraft:enchanting_table",
    "title": "Knowledge",
    "description": "The Knowledge branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "cat_special",
    "parent": "root",
    "icon": "minecraft:stick",
    "title": "Special",
    "description": "The Special branch of the Age of Minecraft.",
    "frame": "goal"
  },
  {
    "id": "townhall",
    "parent": "cat_civic",
    "icon": "minecraft:bell",
    "title": "Townhall",
    "description": "Townhall",
    "frame": "task"
  },
  {
    "id": "townhouse",
    "parent": "cat_civic",
    "icon": "minecraft:oak_door",
    "title": "Townhouse",
    "description": "Townhouse",
    "frame": "task"
  },
  {
    "id": "lumbermill",
    "parent": "cat_extraction",
    "icon": "minecraft:oak_log",
    "title": "Lumbermill",
    "description": "Lumbermill",
    "frame": "task"
  },
  {
    "id": "mine",
    "parent": "lumbermill",
    "icon": "minecraft:wooden_pickaxe",
    "title": "Mine",
    "description": "Mine",
    "frame": "task"
  },
  {
    "id": "quarry",
    "parent": "cat_extraction",
    "icon": "minecraft:gravel",
    "title": "Quarry",
    "description": "Quarry",
    "frame": "task"
  },
  {
    "id": "docks",
    "parent": "lumbermill",
    "icon": "minecraft:oak_boat",
    "title": "Docks",
    "description": "Docks",
    "frame": "task"
  },
  {
    "id": "ice_house",
    "parent": "cat_extraction",
    "icon": "minecraft:ice",
    "title": "Ice House",
    "description": "Ice House",
    "frame": "task"
  },
  {
    "id": "nether_outpost",
    "parent": "cat_extraction",
    "icon": "minecraft:netherrack",
    "title": "Nether Outpost",
    "description": "Nether Outpost",
    "frame": "challenge"
  },
  {
    "id": "stone_cutter",
    "parent": "cat_industry",
    "icon": "minecraft:stonecutter",
    "title": "Stone cutter",
    "description": "Stone cutter",
    "frame": "task"
  },
  {
    "id": "blacksmith",
    "parent": "cat_industry",
    "icon": "minecraft:anvil",
    "title": "Blacksmith",
    "description": "Blacksmith",
    "frame": "task"
  },
  {
    "id": "gold_smith",
    "parent": "coppersmith",
    "icon": "minecraft:gold_ingot",
    "title": "Gold smith",
    "description": "Gold smith",
    "frame": "task"
  },
  {
    "id": "jeweller",
    "parent": "gold_smith",
    "icon": "minecraft:diamond",
    "title": "Jeweller",
    "description": "Jeweller",
    "frame": "goal"
  },
  {
    "id": "coppersmith",
    "parent": "blacksmith",
    "icon": "minecraft:copper_ingot",
    "title": "Coppersmith",
    "description": "Coppersmith",
    "frame": "task"
  },
  {
    "id": "kiln",
    "parent": "cat_industry",
    "icon": "minecraft:brick",
    "title": "Kiln",
    "description": "Kiln",
    "frame": "task"
  },
  {
    "id": "masons_yard",
    "parent": "cat_industry",
    "icon": "minecraft:deepslate",
    "title": "Mason's Yard",
    "description": "Mason's Yard",
    "frame": "task"
  },
  {
    "id": "farm",
    "parent": "cat_agriculture",
    "icon": "minecraft:wheat",
    "title": "Farm",
    "description": "Farm",
    "frame": "task"
  },
  {
    "id": "windmill",
    "parent": "farm",
    "icon": "minecraft:hay_block",
    "title": "Windmill",
    "description": "Windmill",
    "frame": "task"
  },
  {
    "id": "barn",
    "parent": "cat_husbandry",
    "icon": "minecraft:hay_block",
    "title": "Barn",
    "description": "Barn",
    "frame": "task"
  },
  {
    "id": "leather_tanner",
    "parent": "cat_husbandry",
    "icon": "minecraft:leather",
    "title": "Leather tanner",
    "description": "Leather tanner",
    "frame": "task"
  },
  {
    "id": "shepherd",
    "parent": "cat_husbandry",
    "icon": "minecraft:white_wool",
    "title": "Shepherd",
    "description": "Shepherd",
    "frame": "task"
  },
  {
    "id": "spinnery",
    "parent": "cat_husbandry",
    "icon": "minecraft:string",
    "title": "Spinnery",
    "description": "Spinnery",
    "frame": "task"
  },
  {
    "id": "weaver",
    "parent": "spinnery",
    "icon": "minecraft:white_banner",
    "title": "Weaver",
    "description": "Weaver",
    "frame": "task"
  },
  {
    "id": "apiary",
    "parent": "cat_husbandry",
    "icon": "minecraft:honeycomb",
    "title": "Apiary",
    "description": "Apiary",
    "frame": "task"
  },
  {
    "id": "baker",
    "parent": "blacksmith",
    "icon": "minecraft:bread",
    "title": "Baker",
    "description": "Baker",
    "frame": "task"
  },
  {
    "id": "butcher",
    "parent": "lumbermill",
    "icon": "minecraft:cooked_beef",
    "title": "Butcher",
    "description": "Butcher",
    "frame": "task"
  },
  {
    "id": "brewery",
    "parent": "cat_food",
    "icon": "minecraft:brewing_stand",
    "title": "Brewery",
    "description": "Brewery",
    "frame": "task"
  },
  {
    "id": "fisher",
    "parent": "cat_food",
    "icon": "minecraft:fishing_rod",
    "title": "Fisher",
    "description": "Fisher",
    "frame": "task"
  },
  {
    "id": "weapon_smith",
    "parent": "lumbermill",
    "icon": "minecraft:iron_sword",
    "title": "Weapon smith",
    "description": "Weapon smith",
    "frame": "task"
  },
  {
    "id": "fletcher",
    "parent": "cat_crafting",
    "icon": "minecraft:bow",
    "title": "Fletcher",
    "description": "Fletcher",
    "frame": "task"
  },
  {
    "id": "glass_blower",
    "parent": "cat_crafting",
    "icon": "minecraft:glass",
    "title": "Glass blower",
    "description": "Glass blower",
    "frame": "task"
  },
  {
    "id": "painter",
    "parent": "cat_crafting",
    "icon": "minecraft:painting",
    "title": "Painter",
    "description": "Painter",
    "frame": "task"
  },
  {
    "id": "redstone_workshop",
    "parent": "cat_crafting",
    "icon": "minecraft:redstone",
    "title": "Redstone Workshop",
    "description": "Redstone Workshop",
    "frame": "task"
  },
  {
    "id": "bard",
    "parent": "cat_crafting",
    "icon": "minecraft:jukebox",
    "title": "Bard",
    "description": "Bard",
    "frame": "task"
  },
  {
    "id": "armory",
    "parent": "blacksmith",
    "icon": "minecraft:iron_chestplate",
    "title": "Armory",
    "description": "Armory",
    "frame": "task"
  },
  {
    "id": "library",
    "parent": "cat_knowledge",
    "icon": "minecraft:book",
    "title": "Library",
    "description": "Library",
    "frame": "goal"
  },
  {
    "id": "school",
    "parent": "library",
    "icon": "minecraft:bookshelf",
    "title": "School",
    "description": "School",
    "frame": "task"
  },
  {
    "id": "university",
    "parent": "school",
    "icon": "minecraft:obsidian",
    "title": "University",
    "description": "University",
    "frame": "goal"
  },
  {
    "id": "cartographers_guild",
    "parent": "blacksmith",
    "icon": "minecraft:map",
    "title": "Cartographer's Guild",
    "description": "Cartographer's Guild",
    "frame": "task"
  },
  {
    "id": "end_observatory",
    "parent": "cat_knowledge",
    "icon": "minecraft:end_stone",
    "title": "End Observatory",
    "description": "End Observatory",
    "frame": "challenge"
  },
  {
    "id": "custom",
    "parent": "cat_special",
    "icon": "minecraft:stick",
    "title": "Custom",
    "description": "Custom",
    "frame": "task"
  },
];

export function build(): Datapack {
  const d = new Datapack(
    "techdemo",
    latestVersion(),
    "Age of Minecraft tech tree preview (temporary test pack).",
  );

  const criteria = { tick: { trigger: "minecraft:tick" } };
  const requirements = [["tick"]];

  for (const node of NODES) {
    d.advancement(node.id, {
      display: {
        icon: { id: node.icon },
        title: node.title,
        description: node.description,
        frame: node.frame,
        show_toast: false,
        announce_to_chat: false,
        hidden: false,
        ...(node.parent === null ? { background: BACKGROUND } : {}),
      },
      ...(node.parent === null ? {} : { parent: `techdemo:${node.parent}` }),
      criteria,
      requirements,
    });
  }

  return d;
}
