// Regenerates `mcgen/src/models/versions.generated.ts` and
// `mcgen/src/models/recipes.generated.ts` from misode's mcmeta dumps. Run
// `bun run gen` after a new Minecraft release to update the internal version
// models, then `bun run typecheck`.
//
// Sources:
// - https://github.com/misode/mcmeta (summary branch, versions/data.json)
// - https://github.com/misode/mcmeta (data branch, version.json + recipe tree)

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const VERSIONS_URL =
  "https://raw.githubusercontent.com/misode/mcmeta/summary/versions/data.json";
const VERSION_URL = "https://raw.githubusercontent.com/misode/mcmeta/data/version.json";
const TREE_URL =
  "https://api.github.com/repos/misode/mcmeta/git/trees/data?recursive=1";
const ITEMS_URL =
  "https://raw.githubusercontent.com/misode/mcmeta/registries/item/data.min.json";

interface RawVersion {
  id: string;
  type: string;
  stable: boolean;
  data_pack_version: number;
  data_pack_version_minor: number;
  release_time: string;
}

interface RawTree {
  tree: { path: string; type: string }[];
}

const OUT = new URL("../mcgen/src/models/versions.generated.ts", import.meta.url);
const RECIPES_OUT = new URL(
  "../mcgen/src/models/recipes.generated.ts",
  import.meta.url,
);
const ITEMS_OUT = new URL(
  "../mcgen/src/models/items.generated.ts",
  import.meta.url,
);

const res = await fetch(VERSIONS_URL);
if (!res.ok) throw new Error(`Failed to fetch versions: ${res.status}`);
const raw = (await res.json()) as RawVersion[];

const releases = raw
  .filter((v) => v.type === "release" && v.stable)
  .sort((a, b) => Date.parse(b.release_time) - Date.parse(a.release_time));

const latest = releases[0];
if (!latest) throw new Error("No stable releases found");

const entries = releases
  .map(
    (v) =>
      `  ${JSON.stringify(v.id)}: [${v.data_pack_version}, ${v.data_pack_version_minor}],`,
  )
  .join("\n");

const file = `// AUTO-GENERATED by scripts/gen-models.ts — do not edit by hand.
// Minecraft version -> data pack format [major, minor].
export const VERSIONS = {
${entries}
} as const;

export const LATEST = ${JSON.stringify(latest.id)};
`;

writeFileSync(OUT, file);
console.log(
  `Wrote ${releases.length} versions (latest: ${latest.id}) to ${fileURLToPath(OUT)}`,
);

const versionRes = await fetch(VERSION_URL);
if (!versionRes.ok) throw new Error(`Failed to fetch version: ${versionRes.status}`);
const version = (await versionRes.json()) as { id: string };

const treeRes = await fetch(TREE_URL);
if (!treeRes.ok) throw new Error(`Failed to fetch tree: ${treeRes.status}`);
const tree = (await treeRes.json()) as RawTree;

const prefix = "data/minecraft/recipe/";
const recipes = tree.tree
  .filter((entry) => entry.type === "blob" && entry.path.startsWith(prefix))
  .map((entry) => `minecraft:${entry.path.slice(prefix.length, -".json".length)}`)
  .sort();

const recipeFile = `// AUTO-GENERATED by scripts/gen-models.ts — do not edit by hand.
// Vanilla recipe ids for Minecraft ${version.id}.
export const RECIPES = [
${recipes.map((recipe) => `  ${JSON.stringify(recipe)},`).join("\n")}
] as const;
export type RecipeId = (typeof RECIPES)[number];
`;

writeFileSync(RECIPES_OUT, recipeFile);
console.log(
  `Wrote ${recipes.length} recipe ids (${version.id}) to ${fileURLToPath(RECIPES_OUT)}`,
);

const itemsRes = await fetch(ITEMS_URL);
if (!itemsRes.ok) throw new Error(`Failed to fetch items: ${itemsRes.status}`);
const items = ((await itemsRes.json()) as string[]).sort();

const itemsFile = `// AUTO-GENERATED by scripts/gen-models.ts — do not edit by hand.
// Vanilla item ids for Minecraft ${version.id}.
export const ITEM_IDS = [
${items.map((id) => `  "minecraft:${id}",`).join("\n")}
] as const;
`;

writeFileSync(ITEMS_OUT, itemsFile);
console.log(
  `Wrote ${items.length} item ids (${version.id}) to ${fileURLToPath(ITEMS_OUT)}`,
);
