// Regenerates `mcgen/src/models/versions.generated.ts` from misode's mcmeta
// version dump. Run `bun run gen` after a new Minecraft release to update the
// internal version models, then `bun run typecheck`.
//
// Source: https://github.com/misode/mcmeta (summary branch, versions/data.json)

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const VERSIONS_URL =
  "https://raw.githubusercontent.com/misode/mcmeta/summary/versions/data.json";

interface RawVersion {
  id: string;
  type: string;
  stable: boolean;
  data_pack_version: number;
  data_pack_version_minor: number;
  release_time: string;
}

const OUT = new URL("../mcgen/src/models/versions.generated.ts", import.meta.url);

const res = await fetch(VERSIONS_URL);
if (!res.ok) throw new Error(`Failed to fetch versions: ${res.status}`);
const raw = (await res.json()) as RawVersion[];

const releases = raw
  .filter((v) => v.type === "release" && v.stable)
  .sort((a, b) => Date.parse(b.release_time) - Date.parse(a.release_time));

const latest = releases[0];
if (!latest) throw new Error("No stable releases found");

const entries = releases
  .map(
    (v) =>
      `  ${JSON.stringify(v.id)}: [${v.data_pack_version}, ${v.data_pack_version_minor}],`,
  )
  .join("\n");

const file = `// AUTO-GENERATED by scripts/gen-models.ts — do not edit by hand.
// Minecraft version -> data pack format [major, minor].
export const VERSIONS = {
${entries}
} as const;

export const LATEST = ${JSON.stringify(latest.id)};
`;

writeFileSync(OUT, file);
console.log(
  `Wrote ${releases.length} versions (latest: ${latest.id}) to ${fileURLToPath(OUT)}`,
);
