import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  loadDesign,
  buildTree,
  BACKGROUND,
  type TreeNode,
} from "./design.ts";

// Generates packs/techdemo/src/index.ts from packs/aom/DESIGN.md so the in-game
// achievement board always matches the design document.
//
// Run: bun tools/build-techdemo.ts

const here = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(here, "..", "packs/techdemo/src/index.ts");

interface GeneratedNode {
  id: string;
  parent: string | null;
  icon: string;
  title: string;
  description: string;
  frame: "task" | "goal" | "challenge";
}

function describe(node: TreeNode): string {
  if (node.id === "root") {
    return "Age of Minecraft building tech tree preview. Every node is granted for testing.";
  }
  if (node.id.startsWith("cat_")) {
    return `The ${node.title} branch of the Age of Minecraft.`;
  }
  return node.description || node.title;
}

function main(): void {
  const design = loadDesign();
  const { nodes } = buildTree(design);

  const generated: GeneratedNode[] = nodes.map((node) => ({
    id: node.id,
    parent: node.parent,
    icon: node.icon,
    title: node.title,
    description: describe(node),
    frame: node.frame,
  }));

  const body = generated
    .map((node) => JSON.stringify(node, null, 2).replace(/^/gm, "  "))
    .join(",\n");

  const source = `// AUTO-GENERATED by tools/build-techdemo.ts from packs/aom/DESIGN.md.
// Do not edit by hand — run \`bun tools/build-techdemo.ts\` to regenerate.

import { Datapack, latestVersion } from "../../../mcgen/src/index.ts";

const BACKGROUND = ${JSON.stringify(BACKGROUND)};

interface Node {
  readonly id: string;
  readonly parent: string | null;
  readonly icon: string;
  readonly title: string;
  readonly description: string;
  readonly frame: "task" | "goal" | "challenge";
}

const NODES: readonly Node[] = [
${body},
];

export function build(): Datapack {
  const d = new Datapack(
    "techdemo",
    latestVersion(),
    "Age of Minecraft tech tree preview (temporary test pack).",
  );

  const criteria = { tick: { trigger: "minecraft:tick" } };
  const requirements = [["tick"]];

  for (const node of NODES) {
    d.advancement(node.id, {
      display: {
        icon: { id: node.icon },
        title: node.title,
        description: node.description,
        frame: node.frame,
        show_toast: false,
        announce_to_chat: false,
        hidden: false,
        ...(node.parent === null ? { background: BACKGROUND } : {}),
      },
      ...(node.parent === null ? {} : { parent: \`techdemo:\${node.parent}\` }),
      criteria,
      requirements,
    });
  }

  return d;
}
`;

  writeFileSync(OUTPUT, source);
  console.log(`Wrote ${OUTPUT} (${generated.length} advancements)`);
}

main();
